version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: UTC
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      npm-non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: UTC
    open-pull-requests-limit: 10
    groups:
      github-actions-non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: UTC
    open-pull-requests-limit: 5
    groups:
      docker-non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: terraform
    directories:
      - /infra/terraform/bootstrap
      - /infra/terraform/environments/*
    schedule:
      interval: weekly
      day: monday
      time: "06:45"
      timezone: UTC
    open-pull-requests-limit: 10
    groups:
      terraform-non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
